### PR TITLE
Meson lemon

### PR DESCRIPTION
**Pull request by robtaylor**
WIP adding lemon as a subproject to address #3

### CODE REVIEW

**Comment by robtaylor** [comment]
Seems to work!

**Comment by Coloquinte** [comment]
I'm not a big fan of including all the lemon code directly in the repo. What do you think of using a submodule of a mirror like [https://github.com/Coloquinte/lemon](https://github.com/Coloquinte/lemon) as an alternative?

**Comment by robtaylor** [comment]
Ugh, doesnt quite work as meson-python doesn't know where to place it in a wheel

**Comment by Coloquinte** [comment]
It's all header files so maybe we can skip the installing?

**Comment by robtaylor** [comment]
Same here, I included the tarball as there's no obvious git upstream to
use. Happy to use your mirror :)

Yep, skipping install now :)

**Comment by Coloquinte** [comment]
I pushed the submodule version to the meson branch

**Comment by robtaylor** [comment]
ah, this was a merge into meson branch, so i'll close this for now

**Pull request closed without merging**
